//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeNSo.Client.RestClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RestClient.restservice")]
    public interface restservice {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/restservice/CollectionList", ReplyAction="http://tempuri.org/restservice/CollectionListResponse")]
        string[] CollectionList(string database);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/restservice/CollectionCount", ReplyAction="http://tempuri.org/restservice/CollectionCountResponse")]
        int CollectionCount(string database, string collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/restservice/FilteredCollectionCount", ReplyAction="http://tempuri.org/restservice/FilteredCollectionCountResponse")]
        int FilteredCollectionCount(string database, string collection, string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/restservice/GetItem", ReplyAction="http://tempuri.org/restservice/GetItemResponse")]
        string[] GetItem(string database, string collection, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/restservice/Get", ReplyAction="http://tempuri.org/restservice/GetResponse")]
        byte[][] Get(string database, string collection);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface restserviceChannel : DeNSo.Client.RestClient.restservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class restserviceClient : System.ServiceModel.ClientBase<DeNSo.Client.RestClient.restservice>, DeNSo.Client.RestClient.restservice {
        
        public restserviceClient() {
        }
        
        public restserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public restserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public restserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public restserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] CollectionList(string database) {
            return base.Channel.CollectionList(database);
        }
        
        public int CollectionCount(string database, string collection) {
            return base.Channel.CollectionCount(database, collection);
        }
        
        public int FilteredCollectionCount(string database, string collection, string filter) {
            return base.Channel.FilteredCollectionCount(database, collection, filter);
        }
        
        public string[] GetItem(string database, string collection, string id) {
            return base.Channel.GetItem(database, collection, id);
        }
        
        public byte[][] Get(string database, string collection) {
            return base.Channel.Get(database, collection);
        }
    }
}
